/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as StudentRouteImport } from './routes/student'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminManagersRouteImport } from './routes/admin.managers'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ManagerIndexRouteImport } from './routes/manager.index'
import { Route as ManagerConsumptionRouteImport } from './routes/manager.consumption'
import { Route as ManagerMenuRouteImport } from './routes/manager.menu'
import { Route as ManagerPaymentsRouteImport } from './routes/manager.payments'
import { Route as ManagerSubscribersRouteImport } from './routes/manager.subscribers'
import { Route as ManagerTodayRouteImport } from './routes/manager.today'
import { Route as ManagerWastageRouteImport } from './routes/manager.wastage'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentBillRouteImport } from './routes/student.bill'
import { Route as StudentComplaintsRouteImport } from './routes/student.complaints'
import { Route as StudentFeedbackRouteImport } from './routes/student.feedback'
import { Route as StudentHelpRouteImport } from './routes/student.help'
import { Route as StudentMealCalendarRouteImport } from './routes/student.meal-calendar'
import { Route as StudentMealHistoryRouteImport } from './routes/student.meal-history'
import { Route as StudentNotificationsRouteImport } from './routes/student.notifications'
import { Route as StudentPaymentsRouteImport } from './routes/student.payments'
import { Route as StudentPlansRouteImport } from './routes/student.plans'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentSubscriptionRouteImport } from './routes/student.subscription'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminManagersRoute = AdminManagersRouteImport.update({
  id: '/managers',
  path: '/managers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerConsumptionRoute = ManagerConsumptionRouteImport.update({
  id: '/consumption',
  path: '/consumption',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerMenuRoute = ManagerMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerPaymentsRoute = ManagerPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerSubscribersRoute = ManagerSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerTodayRoute = ManagerTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerWastageRoute = ManagerWastageRouteImport.update({
  id: '/wastage',
  path: '/wastage',
  getParentRoute: () => ManagerRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentBillRoute = StudentBillRouteImport.update({
  id: '/bill',
  path: '/bill',
  getParentRoute: () => StudentRoute,
} as any)
const StudentComplaintsRoute = StudentComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => StudentRoute,
} as any)
const StudentFeedbackRoute = StudentFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => StudentRoute,
} as any)
const StudentHelpRoute = StudentHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMealCalendarRoute = StudentMealCalendarRouteImport.update({
  id: '/meal-calendar',
  path: '/meal-calendar',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMealHistoryRoute = StudentMealHistoryRouteImport.update({
  id: '/meal-history',
  path: '/meal-history',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPaymentsRoute = StudentPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPlansRoute = StudentPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSubscriptionRoute = StudentSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => StudentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRouteWithChildren
  '/register': typeof RegisterRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/managers': typeof AdminManagersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/manager/consumption': typeof ManagerConsumptionRoute
  '/manager/menu': typeof ManagerMenuRoute
  '/manager/payments': typeof ManagerPaymentsRoute
  '/manager/subscribers': typeof ManagerSubscribersRoute
  '/manager/today': typeof ManagerTodayRoute
  '/manager/wastage': typeof ManagerWastageRoute
  '/student/bill': typeof StudentBillRoute
  '/student/complaints': typeof StudentComplaintsRoute
  '/student/feedback': typeof StudentFeedbackRoute
  '/student/help': typeof StudentHelpRoute
  '/student/meal-calendar': typeof StudentMealCalendarRoute
  '/student/meal-history': typeof StudentMealHistoryRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/payments': typeof StudentPaymentsRoute
  '/student/plans': typeof StudentPlansRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/subscription': typeof StudentSubscriptionRoute
  '/admin/': typeof AdminIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/managers': typeof AdminManagersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/manager/consumption': typeof ManagerConsumptionRoute
  '/manager/menu': typeof ManagerMenuRoute
  '/manager/payments': typeof ManagerPaymentsRoute
  '/manager/subscribers': typeof ManagerSubscribersRoute
  '/manager/today': typeof ManagerTodayRoute
  '/manager/wastage': typeof ManagerWastageRoute
  '/student/bill': typeof StudentBillRoute
  '/student/complaints': typeof StudentComplaintsRoute
  '/student/feedback': typeof StudentFeedbackRoute
  '/student/help': typeof StudentHelpRoute
  '/student/meal-calendar': typeof StudentMealCalendarRoute
  '/student/meal-history': typeof StudentMealHistoryRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/payments': typeof StudentPaymentsRoute
  '/student/plans': typeof StudentPlansRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/subscription': typeof StudentSubscriptionRoute
  '/admin': typeof AdminIndexRoute
  '/manager': typeof ManagerIndexRoute
  '/student': typeof StudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRouteWithChildren
  '/register': typeof RegisterRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/managers': typeof AdminManagersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/manager/consumption': typeof ManagerConsumptionRoute
  '/manager/menu': typeof ManagerMenuRoute
  '/manager/payments': typeof ManagerPaymentsRoute
  '/manager/subscribers': typeof ManagerSubscribersRoute
  '/manager/today': typeof ManagerTodayRoute
  '/manager/wastage': typeof ManagerWastageRoute
  '/student/bill': typeof StudentBillRoute
  '/student/complaints': typeof StudentComplaintsRoute
  '/student/feedback': typeof StudentFeedbackRoute
  '/student/help': typeof StudentHelpRoute
  '/student/meal-calendar': typeof StudentMealCalendarRoute
  '/student/meal-history': typeof StudentMealHistoryRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/payments': typeof StudentPaymentsRoute
  '/student/plans': typeof StudentPlansRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/subscription': typeof StudentSubscriptionRoute
  '/admin/': typeof AdminIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/help'
    | '/how-it-works'
    | '/login'
    | '/manager'
    | '/register'
    | '/student'
    | '/admin/managers'
    | '/admin/payments'
    | '/admin/plans'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/manager/consumption'
    | '/manager/menu'
    | '/manager/payments'
    | '/manager/subscribers'
    | '/manager/today'
    | '/manager/wastage'
    | '/student/bill'
    | '/student/complaints'
    | '/student/feedback'
    | '/student/help'
    | '/student/meal-calendar'
    | '/student/meal-history'
    | '/student/notifications'
    | '/student/payments'
    | '/student/plans'
    | '/student/profile'
    | '/student/subscription'
    | '/admin/'
    | '/manager/'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/help'
    | '/how-it-works'
    | '/login'
    | '/register'
    | '/admin/managers'
    | '/admin/payments'
    | '/admin/plans'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/manager/consumption'
    | '/manager/menu'
    | '/manager/payments'
    | '/manager/subscribers'
    | '/manager/today'
    | '/manager/wastage'
    | '/student/bill'
    | '/student/complaints'
    | '/student/feedback'
    | '/student/help'
    | '/student/meal-calendar'
    | '/student/meal-history'
    | '/student/notifications'
    | '/student/payments'
    | '/student/plans'
    | '/student/profile'
    | '/student/subscription'
    | '/admin'
    | '/manager'
    | '/student'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/help'
    | '/how-it-works'
    | '/login'
    | '/manager'
    | '/register'
    | '/student'
    | '/admin/managers'
    | '/admin/payments'
    | '/admin/plans'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/manager/consumption'
    | '/manager/menu'
    | '/manager/payments'
    | '/manager/subscribers'
    | '/manager/today'
    | '/manager/wastage'
    | '/student/bill'
    | '/student/complaints'
    | '/student/feedback'
    | '/student/help'
    | '/student/meal-calendar'
    | '/student/meal-history'
    | '/student/notifications'
    | '/student/payments'
    | '/student/plans'
    | '/student/profile'
    | '/student/subscription'
    | '/admin/'
    | '/manager/'
    | '/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  ManagerRoute: typeof ManagerRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/managers': {
      id: '/admin/managers'
      path: '/managers'
      fullPath: '/admin/managers'
      preLoaderRoute: typeof AdminManagersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/consumption': {
      id: '/manager/consumption'
      path: '/consumption'
      fullPath: '/manager/consumption'
      preLoaderRoute: typeof ManagerConsumptionRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/menu': {
      id: '/manager/menu'
      path: '/menu'
      fullPath: '/manager/menu'
      preLoaderRoute: typeof ManagerMenuRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/payments': {
      id: '/manager/payments'
      path: '/payments'
      fullPath: '/manager/payments'
      preLoaderRoute: typeof ManagerPaymentsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/subscribers': {
      id: '/manager/subscribers'
      path: '/subscribers'
      fullPath: '/manager/subscribers'
      preLoaderRoute: typeof ManagerSubscribersRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/today': {
      id: '/manager/today'
      path: '/today'
      fullPath: '/manager/today'
      preLoaderRoute: typeof ManagerTodayRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/wastage': {
      id: '/manager/wastage'
      path: '/wastage'
      fullPath: '/manager/wastage'
      preLoaderRoute: typeof ManagerWastageRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/bill': {
      id: '/student/bill'
      path: '/bill'
      fullPath: '/student/bill'
      preLoaderRoute: typeof StudentBillRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/complaints': {
      id: '/student/complaints'
      path: '/complaints'
      fullPath: '/student/complaints'
      preLoaderRoute: typeof StudentComplaintsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/feedback': {
      id: '/student/feedback'
      path: '/feedback'
      fullPath: '/student/feedback'
      preLoaderRoute: typeof StudentFeedbackRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/help': {
      id: '/student/help'
      path: '/help'
      fullPath: '/student/help'
      preLoaderRoute: typeof StudentHelpRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/meal-calendar': {
      id: '/student/meal-calendar'
      path: '/meal-calendar'
      fullPath: '/student/meal-calendar'
      preLoaderRoute: typeof StudentMealCalendarRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/meal-history': {
      id: '/student/meal-history'
      path: '/meal-history'
      fullPath: '/student/meal-history'
      preLoaderRoute: typeof StudentMealHistoryRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/payments': {
      id: '/student/payments'
      path: '/payments'
      fullPath: '/student/payments'
      preLoaderRoute: typeof StudentPaymentsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/plans': {
      id: '/student/plans'
      path: '/plans'
      fullPath: '/student/plans'
      preLoaderRoute: typeof StudentPlansRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/subscription': {
      id: '/student/subscription'
      path: '/subscription'
      fullPath: '/student/subscription'
      preLoaderRoute: typeof StudentSubscriptionRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface AdminRouteChildren {
  AdminManagersRoute: typeof AdminManagersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminManagersRoute: AdminManagersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ManagerRouteChildren {
  ManagerConsumptionRoute: typeof ManagerConsumptionRoute
  ManagerMenuRoute: typeof ManagerMenuRoute
  ManagerPaymentsRoute: typeof ManagerPaymentsRoute
  ManagerSubscribersRoute: typeof ManagerSubscribersRoute
  ManagerTodayRoute: typeof ManagerTodayRoute
  ManagerWastageRoute: typeof ManagerWastageRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerConsumptionRoute: ManagerConsumptionRoute,
  ManagerMenuRoute: ManagerMenuRoute,
  ManagerPaymentsRoute: ManagerPaymentsRoute,
  ManagerSubscribersRoute: ManagerSubscribersRoute,
  ManagerTodayRoute: ManagerTodayRoute,
  ManagerWastageRoute: ManagerWastageRoute,
  ManagerIndexRoute: ManagerIndexRoute,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

interface StudentRouteChildren {
  StudentBillRoute: typeof StudentBillRoute
  StudentComplaintsRoute: typeof StudentComplaintsRoute
  StudentFeedbackRoute: typeof StudentFeedbackRoute
  StudentHelpRoute: typeof StudentHelpRoute
  StudentMealCalendarRoute: typeof StudentMealCalendarRoute
  StudentMealHistoryRoute: typeof StudentMealHistoryRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentPaymentsRoute: typeof StudentPaymentsRoute
  StudentPlansRoute: typeof StudentPlansRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentSubscriptionRoute: typeof StudentSubscriptionRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentBillRoute: StudentBillRoute,
  StudentComplaintsRoute: StudentComplaintsRoute,
  StudentFeedbackRoute: StudentFeedbackRoute,
  StudentHelpRoute: StudentHelpRoute,
  StudentMealCalendarRoute: StudentMealCalendarRoute,
  StudentMealHistoryRoute: StudentMealHistoryRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentPaymentsRoute: StudentPaymentsRoute,
  StudentPlansRoute: StudentPlansRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentSubscriptionRoute: StudentSubscriptionRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  ManagerRoute: ManagerRouteWithChildren,
  RegisterRoute: RegisterRoute,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
